import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-black'>
        <div className='w-full h-screen flex flex-col opacity-80 bg-black text-white items-center justify-center bg-hero bg-cover'>
          <div className='flex flex-col items-end justify-center relative'>
            <img src='/static/images/main-rect.png' className='absolute left-[-105%] h-[900px]'/>
            <h1 className='font-inter text-8xl font-bold text-white'> AAHVAAN </h1>
            <h2 className='font-inter text-2xl text-[#FFB024] font-medium'> DTU&apos;s Annual Sports Fest </h2>
          </div>
          <div className='flex flex-col'>
            <h2>
              6th - 8th April 2023
            </h2>
          </div>
        </div>
      </main>
    </div>
  )
}
